slides_app/gem/urls.py
from django.conf.urls import url

from . import views

app_name = 'gem'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^getjson', views.getjson, name='get json'),
]
 

slides_app/slides/urls.py
from django.conf.urls import url

from . import views 

app_name = 'slides'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index_lecturer/', views.lecturer, name='index lecturer'),
    url(r'^index_student/', views.student, name='index student'),
    url(r'^lecture/next_page/', views.next_page, name='next page'),
    url(r'^lecture/prev_page/', views.prev_page, name='previous page'),
    url(r'^lecture/vote_current/', views.vote_current, name='vote'),
    #lecture/ must be at the bottom otherwise it will always be matched first
    url(r'^lecture/(?P<isLecturer>[0-1])', views.lecture, name='lecture'),
]

slides_app/slides_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^slides/', include('slides.urls')),
    url(r'^gem/', include('gem.urls')),
    url(r'^admin/', admin.site.urls),
]

slides_app/gem/models.py
from django.db import models

# Create your models here.

slides_app/slides/models.py
import json
from django.db import models
from channels import Group

# Create your models here.

class Current(models.Model):
    slide_name = models.CharField(max_length=200)
    page = models.IntegerField()

    def send_notification(self):
        notification = {
            "id": self.id,
            "slide_name": self.slide_name,
            "page": self.page,
        }
        Group("chat").send({
            "text": json.dumps(notification),
        })
    def save(self, *args, **kwargs):
        result = super(Current, self).save(*args, **kwargs)
        self.send_notification()
        return result


class Slides(models.Model):
    slide_text = models.CharField(max_length=200)
    page = models.IntegerField()
    img_source = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.slide_text +' '+ str(self.page)

    def send_notification(self):
        notification = {
            "id": self.id,
            "slide_name": self.slide_text,
            "votes": self.votes,
        }
        Group("chat").send({
            "text": json.dumps(notification),
        })
    def save(self, *args, **kwargs):
        result = super(Slides, self).save(*args, **kwargs)
        self.send_notification()
        return result

slides_app/gem/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie

# Create your views here.

def index(request):
    return render(request, 'gem/index.html')

@ensure_csrf_cookie
def getjson(request):
    return JsonResponse({ 'foo':'bar'})

  

slides_app/slides/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse

from .models import Current, Slides

# Create your views here.

def index(request):
    return render(request, 'slides/index.html') 

def lecturer(request):
    return HttpResponseRedirect(reverse('slides:lecture', args=[1]))

def student(request):
    return HttpResponseRedirect(reverse('slides:lecture', args=[0]))

def lecture(request, isLecturer):
    current = get_object_or_404(Current, pk=1)
    '''
    qs = Slides.objects.filter(slide_text=current.slide_name)
    qs = qs.filter(page = current.page)
    slide = qs.reverse()[:1]
    return render(request, 'slides/index.html', {'slide': slide})
    '''
    slide = get_object_or_404(Slides, pk=current.page)
    if(isLecturer=='1'):
        return render(request, 'slides/lecture.html', {'slide':slide, 'lecturer':True, 'votes_amplified':slide.votes*5,
                                                       'votes_rest': 100-slide.votes*5})
    else:
        return render(request, 'slides/lecture.html', {'slide':slide, 'student':True, 'votes_amplified':slide.votes*5,
                                                       'votes_rest': 100-slide.votes*5})

def next_page(request):
    current = get_object_or_404(Current, pk=1)
    try:
        slide = Slides.objects.get(page = current.page + 1)
        current.page += 1
        current.save()
    except Slides.DoesNotExist:
        pass
#    return HttpResponseRedirect(reverse('slides:lecture', args=[1]))
    return JsonResponse({'foo':'bar'})

def prev_page(request):
    current = get_object_or_404(Current, pk=1)
    try:
        slide = Slides.objects.get(page = current.page - 1)
        current.page -= 1
        current.save()
    except Slides.DoesNotExist:
        pass
    return HttpResponseRedirect(reverse('slides:lecture', args=[1]))

def vote_current(request):
    current = get_object_or_404(Current, pk=1)
    '''
    qs = Slides.objects.filter(slide_text=current.slide_name)
    qs = qs.filter(page = current.page)
    slide = qs.reverse()[:1]
    return render(request, 'slides/index.html', {'slide': slide})
    '''
    current_slide = get_object_or_404(Slides, pk=current.page)
    current_slide.votes += 1
    current_slide.save()
    return HttpResponseRedirect(reverse('slides:lecture', args=[0]))

slides_app/gem/templates/gem/index.html
{% load staticfiles %}
<html ng-app="gem">

<head>
    <link href="{% static 'gem/bootstrap.min.css' %}" rel="stylesheet" />
    <script type="text/javascript" src="{% static 'gem/angular.min.js' %}"></script>
</head>
<body ng-controller="gemController as gCtrl">
  asdf [[ 1+1 ]]
  <br />
  [[gCtrl.x.foo]]

  <button ng-click="gCtrl.getjson()"> x </button>


  <script>
    var app = angular.module("gem",[]);
    app.config(function($interpolateProvider){
      $interpolateProvider.startSymbol("[[");
      $interpolateProvider.endSymbol("]]");
    });
    app.controller('gemController', ['$http', function($http){
      var store = this;
      this.x = {'foo': 'foo'};

      this.getjson = function(){
        $http.get(window.location.href+'getjson').success(function(data){
          store.x = data;
        });
      };
    }]);
  </script>
<body>
</html>

slides_app/slides/templates/slides/index.html
<h1>Welcome</h1>
<ul>
  <li><a href="{% url 'slides:index lecturer' %}"> lecturer </a></li>
  <li><a href="{% url 'slides:index student' %}"> student </a></li>
</ul>

slides_app/slides/templates/slides/lecture.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lecture</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'slides/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'slides/css/lumen.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'slides/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <!--chat socket example-->
    <script> 
        socket = new WebSocket("ws://127.0.0.1:8000/chat/"); 
        socket.onmessage = function(message) {
              var data = JSON.parse(message.data);
              if(data.votes){
                  var red_width = data.votes * 5;
                  document.getElementById("red_bar").style.width = red_width + '%';
                  document.getElementById("green_bar").style.width = (100-red_width) + '%';
              }
        }
    </script> 
</head>

<body id="page-top" class="index">
    <h1>Slide</h1>
    <img src="{{ slide.img_source }}" height='350' width='500'>

    {% if lecturer %}
    <a href="{% url 'slides:previous page' %}" class="btn btn-primary btn-lg">previous</a>
    <a href="{% url 'slides:next page' %}" class="btn btn-primary btn-lg">next</a>
    {% endif %}
    {% if student %}
    <a href="#" class="btn btn-warning"><i class="fa fa-frown-o fa-3x" aria-hidden="true"></i></a>
    <a href="{% url 'slides:vote' %}" class="btn btn-danger"><i class="fa fa-frown-o fa-3x" aria-hidden="true"></i></a>
    {% endif %}

    <h4>Current class status</h4>
    <div class="progress progress-striped active">
        <div class="progress-bar progress-bar-danger" id="red_bar" style="width: {{ votes_amplified }}%"></div>
        <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
        <div class="progress-bar progress-bar-success" id="green_bar"  style="width: {{ votes_rest }}%"></div>
    </div>        

    <!-- jQuery -->
    <script src="{% static 'slides/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'slides/js/bootstrap.min.js' %}"></script>


</body>

</html>